// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240630231932_CriacaoTabelaAccrual")]
    partial class CriacaoTabelaAccrual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.AccrualAggregate.Accrual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccrualDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accrual_date");

                    b.Property<string>("AccrualStatus")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("accrual_status");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_number");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("partner");

                    b.HasKey("Id");

                    b.ToTable("accruals", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
